[project]
name = "django-tutorial"
version = "0.1.0"
description = "Following django-tutorial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "django>=5.2.6",
]
